#include "Support/LLVM.h"
#include "FSM/FSMOps.h"

using namespace mlir;
using namespace fsm;


//===----------------------------------------------------------------------===//
// TableGen generated logic
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "FSM/FSM.cpp.inc"
